<a href="https://colab.research.google.com/github/nfmanios-debug/Programacion_para_Ciencia_de_Datos-/blob/main/Taller05.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Taller 05 - Seleccionar datos**
---
<img src = "https://pandas.pydata.org/static/img/pandas.svg" alt = "pandas Logo" width = "70%">  </img>

En este taller revisaremos las operaciones de lectura y selección de datos en **pandas**. Repasaremos los conceptos relacionados
con dataframes y la importancia de los mismos en el análisis de datos.

In [21]:
# Importar Pandas y guarda en la variable df el archivo Excel ubicado en: https://github.com/luiscobo/poo/raw/refs/heads/main/Personas.xlsx
import pandas as pd
dfp = pd.read_excel("https://github.com/luiscobo/poo/raw/refs/heads/main/Personas.xlsx")
df1 = display(pd.read_excel("https://github.com/luiscobo/poo/raw/refs/heads/main/Personas.xlsx"))

,Cédula,Nombres,Edad,Genero,No de hijos,Nivel Educativo,Estrato Socio,Ingresos,Peso,Talla,Fuma,Usa Lentes,Tiene Casa,Tiene Automovil
0,1001023688,Caleb Figueroa,39,HOMBRE,1,SECUNDARIA,2,3182000,64,183,NO,NO,NO,NO
1,1011835272,Jonathan Perkins,46,HOMBRE,3,POSTGRADO,4,5607000,90,163,SI,SI,NO,NO
2,1012005757,John James,40,HOMBRE,0,SECUNDARIA,3,1633000,78,174,NO,NO,NO,SI
3,1012170500,James Fuentes,45,HOMBRE,3,PRIMARIA,3,2211000,81,162,NO,NO,NO,NO
4,1015693396,Adam Fischer,46,HOMBRE,3,PREGRADO,2,4149000,69,166,SI,NO,NO,NO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
514,1988507026,Rebekah Page,36,MUJER,1,POSTGRADO,3,3886000,91,166,SI,SI,SI,NO
515,1992081101,Erika Love,29,MUJER,2,POSTGRADO,2,3424000,70,173,SI,SI,NO,NO
516,1993697068,Misty Barry,33,MUJER,1,SECUNDARIA,2,3079000,59,163,SI,SI,NO,SI
517,1994927121,Ruth Davis,28,MUJER,2,POSTGRADO,3,3380000,70,168,NO,NO,SI,NO
518,1999387013,Kimberly Ortega,49,MUJER,0,SECUNDARIA,2,5410000,69,168,SI,NO,SI,SI

In [26]:
# Obtener los nombres de las columnas
dfp.columns

Index(['Cédula', 'Nombres', 'Edad', 'Genero', 'No de hijos', 'Nivel Educativo',
       'Estrato Socio', 'Ingresos', 'Peso', 'Talla', 'Fuma', 'Usa Lentes',
       'Tiene Casa', 'Tiene Automovil'],
      dtype='object')

In [28]:
# Obtener un resumen de la información de las columnas
dfp.dtypes

Cédula              int64
Nombres            object
Edad                int64
Genero             object
No de hijos         int64
Nivel Educativo    object
Estrato Socio       int64
Ingresos            int64
Peso                int64
Talla               int64
Fuma               object
Usa Lentes         object
Tiene Casa         object
Tiene Automovil    object
dtype: object

In [29]:
# Presentar las primeras 10 filas del dataframe

dfp.head(10)

,Cédula,Nombres,Edad,Genero,No de hijos,Nivel Educativo,Estrato Socio,Ingresos,Peso,Talla,Fuma,Usa Lentes,Tiene Casa,Tiene Automovil
0,1001023688,Caleb Figueroa,39,HOMBRE,1,SECUNDARIA,2,3182000,64,183,NO,NO,NO,NO
1,1011835272,Jonathan Perkins,46,HOMBRE,3,POSTGRADO,4,5607000,90,163,SI,SI,NO,NO
2,1012005757,John James,40,HOMBRE,0,SECUNDARIA,3,1633000,78,174,NO,NO,NO,SI
3,1012170500,James Fuentes,45,HOMBRE,3,PRIMARIA,3,2211000,81,162,NO,NO,NO,NO
4,1015693396,Adam Fischer,46,HOMBRE,3,PREGRADO,2,4149000,69,166,SI,NO,NO,NO
5,1016796462,Clayton Smith,52,HOMBRE,2,PREGRADO,2,3117000,98,177,SI,SI,SI,NO
6,1026386806,Victor Holland,38,HOMBRE,2,POSTGRADO,3,3454000,76,178,NO,SI,SI,SI
7,1026911435,Richard Carter,38,HOMBRE,3,PREGRADO,2,5472000,87,175,SI,SI,SI,SI
8,1030125450,Joshua Wright,46,HOMBRE,3,PRIMARIA,2,2771000,68,164,NO,SI,SI,SI
9,1034145123,Steven Mccoy,31,HOMBRE,1,POSTGRADO,2,4318000,73,176,SI,NO,SI,NO

In [30]:
# Mostrar toda la columna de nombres
dfp.Nombres

0        Caleb Figueroa
1      Jonathan Perkins
2            John James
3         James Fuentes
4          Adam Fischer
             ...
514        Rebekah Page
515          Erika Love
516         Misty Barry
517          Ruth Davis
518     Kimberly Ortega
Name: Nombres, Length: 519, dtype: object

In [35]:
# Mostrar las primeras 10 filas de la columna que tiene el número de hijos

dfh = display(dfp["No de hijos"].head(10))

0    1
1    3
2    0
3    3
4    3
5    2
6    2
7    3
8    3
9    1
Name: No de hijos, dtype: int64

In [39]:
# Mostar la cédula, nombre y edad de las primeras 5 personas del dataframe
dfc = display(dfp[['Cédula','Nombres','Edad']].head(5))

       Cédula           Nombres  Edad
0  1001023688    Caleb Figueroa    39
1  1011835272  Jonathan Perkins    46
2  1012005757        John James    40
3  1012170500     James Fuentes    45
4  1015693396      Adam Fischer    46

In [40]:
# Presentar la cédula y estado civil de las últimas 10 personas
dfl = display(dfp[['Cédula','Estrato Socio']].tail(10))

         Cédula  Estrato Socio
509  1974761457              4
510  1977444764              4
511  1982699243              4
512  1986546436              2
513  1987223851              2
514  1988507026              3
515  1992081101              2
516  1993697068              2
517  1994927121              3
518  1999387013              2

In [41]:
# Presentar las estadísticas de las columnas edad e ingresos de todas las personas del dataframe

dfs = display(dfp[['Cédula','Edad','Ingresos']].describe())

             Cédula        Edad      Ingresos
count  5.190000e+02  519.000000  5.190000e+02
mean   1.522008e+09   38.847784  3.655441e+06
std    2.892209e+08   10.651823  1.190801e+06
min    1.001024e+09   21.000000  1.604000e+06
25%    1.268997e+09   30.000000  2.624500e+06
50%    1.545317e+09   39.000000  3.626000e+06
75%    1.761916e+09   48.000000  4.672500e+06
max    1.999925e+09   57.000000  5.687000e+06

In [46]:
# Presentar las estadísticas de las columnas peso y talla pero de solo
# las primeras 50 personas del dataframe
dfs2 = display(dfp[['Peso','Talla','Ingresos']].head(50).describe())

,Cédula,Nombres,Edad,Genero,No de hijos,Nivel Educativo,Estrato Socio,Ingresos,Peso,Talla,Fuma,Usa Lentes,Tiene Casa,Tiene Automovil
0,1001023688,Caleb Figueroa,39,HOMBRE,1,SECUNDARIA,2,3182000,64,183,NO,NO,NO,NO
1,1011835272,Jonathan Perkins,46,HOMBRE,3,POSTGRADO,4,5607000,90,163,SI,SI,NO,NO
2,1012005757,John James,40,HOMBRE,0,SECUNDARIA,3,1633000,78,174,NO,NO,NO,SI
3,1012170500,James Fuentes,45,HOMBRE,3,PRIMARIA,3,2211000,81,162,NO,NO,NO,NO
4,1015693396,Adam Fischer,46,HOMBRE,3,PREGRADO,2,4149000,69,166,SI,NO,NO,NO
5,1016796462,Clayton Smith,52,HOMBRE,2,PREGRADO,2,3117000,98,177,SI,SI,SI,NO
6,1026386806,Victor Holland,38,HOMBRE,2,POSTGRADO,3,3454000,76,178,NO,SI,SI,SI
7,1026911435,Richard Carter,38,HOMBRE,3,PREGRADO,2,5472000,87,175,SI,SI,SI,SI
8,1030125450,Joshua Wright,46,HOMBRE,3,PRIMARIA,2,2771000,68,164,NO,SI,SI,SI
9,1034145123,Steven Mccoy,31,HOMBRE,1,POSTGRADO,2,4318000,73,176,SI,NO,SI,NO

            Peso       Talla      Ingresos
count  50.000000   50.000000  5.000000e+01
mean   79.040000  171.280000  3.532340e+06
std    11.071124    6.487162  1.166271e+06
min    59.000000  161.000000  1.612000e+06
25%    69.250000  166.000000  2.783500e+06
50%    79.500000  171.500000  3.410000e+06
75%    87.000000  177.000000  4.223500e+06
max    98.000000  183.000000  5.607000e+06

In [49]:
# Muestra los datos de la persona ubicada en el índice o posición 100 del dataframe
# Puede usar la operación loc o iloc

dfs2 = display(dfp.iloc[100])

Cédula                  1444804844
Nombres            Michael Sellers
Edad                            55
Genero                      HOMBRE
No de hijos                      0
Nivel Educativo          POSTGRADO
Estrato Socio                    4
Ingresos                   2662000
Peso                            58
Talla                          173
Fuma                            SI
Usa Lentes                      SI
Tiene Casa                      SI
Tiene Automovil                 NO
Name: 100, dtype: object

In [52]:
# Muestre todas las columnas de las personas ubicadas en las posiciones de la 277 a la 286
dfi = display(dfp.loc[277:286])

,Cédula,Nombres,Edad,Genero,No de hijos,Nivel Educativo,Estrato Socio,Ingresos,Peso,Talla,Fuma,Usa Lentes,Tiene Casa,Tiene Automovil
277,1057128266,Tamara Patrick,57,MUJER,0,PRIMARIA,4,3563000,62,180,SI,NO,SI,NO
278,1060262767,Joanna Downs,56,MUJER,1,PRIMARIA,3,3351000,87,174,SI,NO,SI,SI
279,1062969596,Christine Gonzalez,24,MUJER,1,PREGRADO,2,2199000,84,162,NO,NO,SI,NO
280,1065010607,Angela Gomez,44,MUJER,1,SECUNDARIA,3,3384000,63,171,NO,NO,NO,SI
281,1071928811,Sarah Young,52,MUJER,2,SECUNDARIA,3,1674000,95,164,NO,NO,SI,SI
282,1073671819,Emily Briggs,43,MUJER,0,PREGRADO,4,1934000,71,164,SI,NO,SI,NO
283,1075921947,Kerri Roberts,27,MUJER,3,PREGRADO,4,2577000,98,173,NO,NO,NO,NO
284,1083532517,Susan Valdez,25,MUJER,0,SECUNDARIA,2,4693000,72,172,SI,NO,SI,SI
285,1085422030,Courtney Sloan,31,MUJER,1,POSTGRADO,4,5256000,61,183,SI,SI,NO,NO
286,1086576916,Rachael Miller,52,MUJER,3,PREGRADO,2,1985000,72,168,SI,NO,SI,NO

In [59]:
# Muestre solamente la cédula de la persona ubicada en la fila 183
dfi183 = display(dfp.loc[183, 'Cédula'])

np.int64(1708715904)

In [81]:
# Muestre la cedula, nombre y estado civil de las personas ubicadas entre las filas
# 417 y 423 del dataframe

df417 = display(dfp.loc[417:423, ['Cédula', 'Nombres', 'Estrato Socio']])

         Cédula          Nombres  Estrato Socio
417  1650117000     Penny Butler              4
418  1654714481      Kelly Ayers              2
419  1657096154  Patricia Greene              4
420  1661286254  Stephanie Davis              3
421  1665017495    Rachel Willis              4
422  1668465285      Lori Bryant              4
423  1673321609      Laura Payne              4

In [83]:
# Muestre las estadísticas de la columna edad de las personas
# ubicadas entre las filas 300 y 399
dfi300 = display(dfp.loc[417:423, ['Edad']].describe())

            Edad
count   7.000000
mean   47.714286
std    10.387722
min    27.000000
25%    45.500000
50%    48.000000
75%    55.500000
max    57.000000

In [89]:
# Usando las operaciones de agregación (sección 11 del cheat sheer)
# Muestre la suma de los ingresos de todas las personas

dfa = display(dfp.Ingresos.sum())

np.int64(1897174000)

In [92]:
# Ahora muestre la suma de los ingresos de las personas
# ubicadas entre las filas 100 y 199 del data frames
dfa2 = display(dfp.loc[100:199, ['Ingresos']].sum())

Ingresos    370306000
dtype: int64

In [95]:
# Muestre el promedio de edad de las personas ubicadas
# entre las filas 200 y 250 del data frame
df3 = display(dfp.loc[200:250, ['Edad']].mean())

Edad    35.627451
dtype: float64

In [96]:
# Determine la edad más grande (use la operación max)
# entre las personas ubicadas en las primeras 100 filas
df4 = display(dfp.loc[0:100, ['Edad']].max())

Edad    57
dtype: int64

In [101]:
# Encuentre el número de elementos únicos (use nunique)
# que se pueden encontrar dentro de la columna nivel educativo
df5 = display(dfp['Nivel Educativo'].nunique())

4

In [102]:
# Encuentre la desviación estándar (use std) del peso y la talla
# de las personas ubicada entre la posición 300 y el final del dataframe
df4 = display(dfp.loc[300:, ['Peso','Talla']].std())

Peso     11.319696
Talla     6.250168
dtype: float64