# **Taller 05 - Seleccionar datos**
---
<img src = "https://pandas.pydata.org/static/img/pandas.svg" alt = "pandas Logo" width = "70%">  </img>

En este taller revisaremos las operaciones de lectura y selección de datos en **pandas**. Repasaremos los conceptos relacionados
con dataframes y la importancia de los mismos en el análisis de datos.

In [89]:
# Importar Pandas y guarda en la variable df el archivo Excel ubicado en: https://github.com/luiscobo/poo/raw/refs/heads/main/Personas.xlsx
import pandas as pd
df1 = display(pd.read_excel("https://github.com/luiscobo/poo/raw/refs/heads/main/Personas.xlsx"))
dfd = df1

,Cédula,Nombres,Edad,Genero,No de hijos,Nivel Educativo,Estrato Socio,Ingresos,Peso,Talla,Fuma,Usa Lentes,Tiene Casa,Tiene Automovil
0,1001023688,Caleb Figueroa,39,HOMBRE,1,SECUNDARIA,2,3182000,64,183,NO,NO,NO,NO
1,1011835272,Jonathan Perkins,46,HOMBRE,3,POSTGRADO,4,5607000,90,163,SI,SI,NO,NO
2,1012005757,John James,40,HOMBRE,0,SECUNDARIA,3,1633000,78,174,NO,NO,NO,SI
3,1012170500,James Fuentes,45,HOMBRE,3,PRIMARIA,3,2211000,81,162,NO,NO,NO,NO
4,1015693396,Adam Fischer,46,HOMBRE,3,PREGRADO,2,4149000,69,166,SI,NO,NO,NO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
514,1988507026,Rebekah Page,36,MUJER,1,POSTGRADO,3,3886000,91,166,SI,SI,SI,NO
515,1992081101,Erika Love,29,MUJER,2,POSTGRADO,2,3424000,70,173,SI,SI,NO,NO
516,1993697068,Misty Barry,33,MUJER,1,SECUNDARIA,2,3079000,59,163,SI,SI,NO,SI
517,1994927121,Ruth Davis,28,MUJER,2,POSTGRADO,3,3380000,70,168,NO,NO,SI,NO
518,1999387013,Kimberly Ortega,49,MUJER,0,SECUNDARIA,2,5410000,69,168,SI,NO,SI,SI

AttributeError: 'NoneType' object has no attribute 'cache'

In [84]:
# Obtener los nombres de las columnas
import pandas as pd
dfc = display(pd.read_excel("https://github.com/luiscobo/poo/raw/refs/heads/main/Personas.xlsx").columns)

Index(['Cédula', 'Nombres', 'Edad', 'Genero', 'No de hijos', 'Nivel Educativo',
       'Estrato Socio', 'Ingresos', 'Peso', 'Talla', 'Fuma', 'Usa Lentes',
       'Tiene Casa', 'Tiene Automovil'],
      dtype='object')

In [85]:
# Obtener un resumen de la información de las columnas
import pandas as pd
dfci = display(pd.read_excel("https://github.com/luiscobo/poo/raw/refs/heads/main/Personas.xlsx").dtypes)

Cédula              int64
Nombres            object
Edad                int64
Genero             object
No de hijos         int64
Nivel Educativo    object
Estrato Socio       int64
Ingresos            int64
Peso                int64
Talla               int64
Fuma               object
Usa Lentes         object
Tiene Casa         object
Tiene Automovil    object
dtype: object

In [86]:
# Presentar las primeras 10 filas del dataframe

df2 = display(pd.read_excel("https://github.com/luiscobo/poo/raw/refs/heads/main/Personas.xlsx").head(10))

,Cédula,Nombres,Edad,Genero,No de hijos,Nivel Educativo,Estrato Socio,Ingresos,Peso,Talla,Fuma,Usa Lentes,Tiene Casa,Tiene Automovil
0,1001023688,Caleb Figueroa,39,HOMBRE,1,SECUNDARIA,2,3182000,64,183,NO,NO,NO,NO
1,1011835272,Jonathan Perkins,46,HOMBRE,3,POSTGRADO,4,5607000,90,163,SI,SI,NO,NO
2,1012005757,John James,40,HOMBRE,0,SECUNDARIA,3,1633000,78,174,NO,NO,NO,SI
3,1012170500,James Fuentes,45,HOMBRE,3,PRIMARIA,3,2211000,81,162,NO,NO,NO,NO
4,1015693396,Adam Fischer,46,HOMBRE,3,PREGRADO,2,4149000,69,166,SI,NO,NO,NO
5,1016796462,Clayton Smith,52,HOMBRE,2,PREGRADO,2,3117000,98,177,SI,SI,SI,NO
6,1026386806,Victor Holland,38,HOMBRE,2,POSTGRADO,3,3454000,76,178,NO,SI,SI,SI
7,1026911435,Richard Carter,38,HOMBRE,3,PREGRADO,2,5472000,87,175,SI,SI,SI,SI
8,1030125450,Joshua Wright,46,HOMBRE,3,PRIMARIA,2,2771000,68,164,NO,SI,SI,SI
9,1034145123,Steven Mccoy,31,HOMBRE,1,POSTGRADO,2,4318000,73,176,SI,NO,SI,NO

In [90]:
# Mostrar toda la columna de nombres

dfd.nombres

AttributeError: 'NoneType' object has no attribute 'nombres'

In [ ]:
# Mostrar las primeras 10 filas de la columna que tiene el número de hijos

In [ ]:
# Mostar la cédula, nombre y edad de las primeras 5 personas del dataframe

In [ ]:
# Presentar la cédula y estado civil de las últimas 10 personas

In [ ]:
# Presentar las estadísticas de las columnas edad e ingresos de todas las personas del dataframe

In [ ]:
# Presentar las estadísticas de las columnas peso y talla pero de solo
# las primeras 50 personas del dataframe

In [ ]:
# Muestra los datos de la persona ubicada en el índice o posición 100 del dataframe
# Puede usar la operación loc o iloc

In [ ]:
# Muestre todas las columnas de las personas ubicadas en las posiciones de la 277 a la 286

In [ ]:
# Muestre solamente la cédula de la persona ubicada en la fila 183

In [ ]:
# Muestre la cedula, nombre y estado civil de las personas ubicadas entre las filas
# 417 y 423 del dataframe

In [ ]:
# Muestre las estadísticas de la columna edad de las personas
# ubicadas entre las filas 300 y 399

In [ ]:
# Usando las operaciones de agregación (sección 11 del cheat sheer)
# Muestre la suma de los ingresos de todas las personas

In [ ]:
# Ahora muestre la suma de los ingresos de las personas
# ubicadas entre las filas 100 y 199 del data frames

In [ ]:
# Muestre el promedio de edad de las personas ubicadas
# entre las filas 200 y 250 del data frame

In [ ]:
# Determine la edad más grande (use la operación max)
# entre las personas ubicadas en las primeras 100 filas

In [ ]:
# Encuentre el número de elementos únicos (use nunique)
# que se pueden encontrar dentro de la columna nivel educativo

In [ ]:
# Encuentre la desviación estándar (use std) del peso y la talla
# de las personas ubicada entre la posición 300 y el final del dataframe